version: '3'
services:

  dsw_server:
    image: datastewardshipwizard/wizard-server:2.6.0
    restart: always
    hostname: dsw_server
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
      - mongo
    volumes:
      - ./server/application.yml:/application/engine-wizard/config/application.yml:ro
      - ./server/integration.yml:/application/engine-wizard/config/integration.yml:ro

  dsw_client:
    image: datastewardshipwizard/wizard-client:2.6.0
    restart: always
    hostname: dsw_client
    ports:
      - 8080:80
    environment:
      API_URL: http://localhost:3000

  docworker:
    image: datastewardshipwizard/document-worker:2.6.0
    restart: always
    depends_on:
      - rabbitmq
    volumes:
      - ./docworker/config.yml:/app/config.yml:ro

  mongo:
    image: mongo:4.2.3
    restart: always
    # (!) Expose only for debugging locally or set-up authentication
    ports:
      - 27017:27017
    # command: mongod --auth
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: secure-password
    volumes:
      - mongo-data:/data/db
    # OR
    # - ./mongo/data:/data/db

  rabbitmq:
    image: rabbitmq:3.8.2-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  agraph:
    # TODO: secured port with certs?
    image: franzinc/agraph:v7.0.1
    restart: always
    ports:
      - 10000-10035:10000-10035
    hostname: agraph
    shm_size: '1gb'
    volumes:
      - agraph-data:/agraph/data
    # OR
    #  - ./allegrograph/data:/agraph/data/
      - ./allegrograph/agraph.cfg:/agraph/etc/agraph.cfg

  submission_service:
    image: datastewardshipwizard/triple-store-submission-service:develop  # TODO: will be 1.2.0 probably
    restart: always
    hostname: submission_service
    volumes:
      - ./submission-service/config.yml:/app/config.yml:ro

volumes:
  mongo-data:
  agraph-data:
